[build]
  publish = "dist/TrackGoal-app/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/TrackGoal-app/browser" 